version = 0.1
extensions = ["chomp@0.1:swc", "./svelte.js", "chomp@0.1:jspm"]

[env]
PACKAGE_MANAGER = "pnpm"

[template-options.npm]
auto-install = true

[[task]]
name = "build"
deps = [":build:html"]

[[task]]
name = "build:html"
template = "jspm"
target = "lib/index.html"
deps = ["src/index.html", ":build:svelte", ":build:typescript"]
[task.template-options]
env = ["browser", "development"]
preload = false
integrity = false
whitespace = true

[[task]]
name = "build:typescript"
template = "swc"
target = "lib/#.js"
deps = ["src/#.ts"]

[[task]]
name = "build:svelte"
template = "svelte"
target = "lib/#.js"
deps = ["src/#.svelte"]
[task.template-options]
svelte-config = true
